SEED: 42

EXP_NAME: "Diffusion AD MVTecAD_carpet"

DATASET:
  name: "MVTecAD"
  datadir: "./dataset/mvtec_ad/"
  target: "carpet" # Specify target name
  img_size: 256 # This could be any integer, depending on your use-case
  self_aug: "self-augmentation"
  normalize: False

DATALOADER:
  batch_size: 6
  num_workers: 4

TRAIN:
  use_wandb: True # True if using Weights and Biases for logging
  focal_gamma: 2.0 # Focal loss gamma parameter
  focal_alpha: 0.25 # Focal loss alpha parameter
  num_training_steps: 10000
  mse_weight: 0.5
  sml1_weight: 0.5
  focal_weight: 0.5

OPTIMIZER:
  lr: 0.0001 # Learning rate
  weight_decay: 0.0005

SCHEDULER:
  use_scheduler: True
  min_lr: 0.00001
  warmup_ratio: 0.1

LOG:
  log_interval: 100 # Log every 100 steps
  eval_interval: 1000 # Evaluate every 1000 steps

RESULT:
  savedir: "./result/mvtec_ad/carpet" # Directory where results will be saved
